include:
  - docker
  - tachiproxy_mangachan.disk

tachiproxy_mangachan_dir:
  file.directory:
    - name: /opt/tachiproxy-mangachan
    - user: root
    - group: root
    - mode: '0750'
    - makedirs: True

# postgres's container runs as uid 70 (postgres:17-alpine); the data dir
# must be writable by it since docker doesn't chown bind mounts like it does
# named volumes.
tachiproxy_mangachan_postgres_dir:
  file.directory:
    - name: /data/tachiproxy-mangachan/postgres
    - user: 70
    - group: 70
    - mode: '0750'
    - makedirs: True
    - require:
      - mount: tachiproxy_mangachan_data_mounted

tachiproxy_mangachan_compose:
  file.managed:
    - name: /opt/tachiproxy-mangachan/docker-compose.yml
    - source: salt://tachiproxy_mangachan/files/docker-compose.yml
    - user: root
    - group: root
    - mode: '0644'
    - require:
      - file: tachiproxy_mangachan_dir

tachiproxy_mangachan_env:
  file.managed:
    - name: /opt/tachiproxy-mangachan/.env
    - source: salt://tachiproxy_mangachan/files/env.jinja
    - template: jinja
    - user: root
    - group: root
    - mode: '0600'
    - require:
      - file: tachiproxy_mangachan_dir

# mitmproxy's CA (generated by vm-tachiproxy's proxy container) so api/worker
# can validate TLS when routing scrape traffic through versioned-proxy's
# intercepting proxy -- see VERSION_PROXY_CA_PATH in files/env.jinja.
tachiproxy_mangachan_ca:
  file.managed:
    - name: /opt/tachiproxy-mangachan/ca.pem
    - source: salt://tachiproxy_mangachan/files/ca.pem
    - user: root
    - group: root
    - mode: '0644'
    - require:
      - file: tachiproxy_mangachan_dir

# One-time migration of the old default-local `tachiproxy-mangachan_postgres_data`
# docker volume (pre-disk.sls deploys) onto the scsi1 data disk: copies its
# contents into the bind-mount target the compose file's driver_opts now
# points the *same-named* volume at, then drops the old volume so `docker
# compose up` can recreate it there instead of erroring over mismatched
# driver_opts on an existing volume. Stops the stack first so the copy is
# consistent; copies via a throwaway container so it works regardless of
# docker's data-root path.
# Guarded to run at most once: skipped once the bind mount already has data
# (which also covers "already migrated" since the old volume gets removed
# below), and skipped entirely on hosts that never had the old volume
# (fresh deploys).
tachiproxy_mangachan_migrate_postgres_data:
  cmd.run:
    - name: >
        docker compose stop postgres api worker &&
        docker run --rm
        -v tachiproxy-mangachan_postgres_data:/from:ro
        -v /data/tachiproxy-mangachan/postgres:/to
        alpine sh -c 'cp -a /from/. /to/ && chown -R 70:70 /to' &&
        docker volume rm tachiproxy-mangachan_postgres_data
    - cwd: /opt/tachiproxy-mangachan
    - onlyif:
      - docker volume inspect tachiproxy-mangachan_postgres_data
      - test -z "$(ls -A /data/tachiproxy-mangachan/postgres)"
    - require:
      - service: docker_service
      - file: tachiproxy_mangachan_compose
      - file: tachiproxy_mangachan_postgres_dir

tachiproxy_mangachan_up:
  cmd.run:
    - name: docker compose up -d
    - cwd: /opt/tachiproxy-mangachan
    - require:
      - service: docker_service
      - file: tachiproxy_mangachan_compose
      - file: tachiproxy_mangachan_env
      - file: tachiproxy_mangachan_ca
      - file: tachiproxy_mangachan_postgres_dir
      - cmd: tachiproxy_mangachan_migrate_postgres_data
