include:
  - docker

tachiproxy_mangachan_dir:
  file.directory:
    - name: /opt/tachiproxy-mangachan
    - user: root
    - group: root
    - mode: '0750'
    - makedirs: True

tachiproxy_mangachan_compose:
  file.managed:
    - name: /opt/tachiproxy-mangachan/docker-compose.yml
    - source: salt://tachiproxy_mangachan/files/docker-compose.yml
    - user: root
    - group: root
    - mode: '0644'
    - require:
      - file: tachiproxy_mangachan_dir

tachiproxy_mangachan_env:
  file.managed:
    - name: /opt/tachiproxy-mangachan/.env
    - source: salt://tachiproxy_mangachan/files/env.jinja
    - template: jinja
    - user: root
    - group: root
    - mode: '0600'
    - require:
      - file: tachiproxy_mangachan_dir

# mitmproxy's CA (generated by vm-tachiproxy's proxy container) so api/worker
# can validate TLS when routing scrape traffic through versioned-proxy's
# intercepting proxy -- see VERSION_PROXY_CA_PATH in files/env.jinja.
tachiproxy_mangachan_ca:
  file.managed:
    - name: /opt/tachiproxy-mangachan/ca.pem
    - source: salt://tachiproxy_mangachan/files/ca.pem
    - user: root
    - group: root
    - mode: '0644'
    - require:
      - file: tachiproxy_mangachan_dir

tachiproxy_mangachan_up:
  cmd.run:
    - name: docker compose up -d
    - cwd: /opt/tachiproxy-mangachan
    - require:
      - service: docker_service
      - file: tachiproxy_mangachan_compose
      - file: tachiproxy_mangachan_env
      - file: tachiproxy_mangachan_ca
